//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace urNotice.Common.Infrastructure.Model.urNoticeAnalyticsContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoogleApiCheckLastSynced
    {
        public int Id { get; set; }
        public string emailId { get; set; }
        public string lastContactUpdated { get; set; }
    }
}
