//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace urNotice.Common.Infrastructure.Model.urNoticeAnalyticsContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoogleApiContact
    {
        public int Id { get; set; }
        public string emailId { get; set; }
        public System.DateTime createdDate { get; set; }
        public int startIndex { get; set; }
        public int itemPerPage { get; set; }
        public string lastContactUpdated { get; set; }
        public string entryListString { get; set; }
        public bool isSolrUpdated { get; set; }
        public bool isVirtualFriendListUpdated { get; set; }
    }
}
