//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace urNoticeAnalytics.Models.urNoticeAnalyticContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class VirtualFriendList
    {
        public int Id { get; set; }
        public string id1 { get; set; }
        public string id2 { get; set; }
        public string type { get; set; }
        public string source { get; set; }
        public bool isSolrUpdated { get; set; }
        public string name1 { get; set; }
        public string name2 { get; set; }
    }
}
