//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace urNotice.Common.Infrastructure.Model.urNoticeAuthContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyDesignationInfo
    {
        public int Id { get; set; }
        public string companyId { get; set; }
        public string locationId { get; set; }
        public string designationId { get; set; }
        public System.DateTime lastUpdated { get; set; }
        public double avgSalary { get; set; }
        public int numOfSalary { get; set; }
        public bool isVerified { get; set; }
        public string verifiedBy { get; set; }
        public Nullable<bool> isDBSynced { get; set; }
    }
}
