//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace urNotice.Common.Infrastructure.Model.urNoticeAuthContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanySubPart
    {
        public int Id { get; set; }
        public string companyId { get; set; }
        public string locationId { get; set; }
        public string website { get; set; }
        public Nullable<long> size { get; set; }
        public string description { get; set; }
        public System.DateTime lastUpdated { get; set; }
        public string lastUpdatedBy { get; set; }
        public string CompanyName { get; set; }
        public double averageRating { get; set; }
        public long totalNumberOfRatings { get; set; }
        public long totalReviews { get; set; }
        public bool isPrimary { get; set; }
        public string logoUrl { get; set; }
        public string squareLogoUrl { get; set; }
        public string specialities { get; set; }
        public string guid { get; set; }
        public double avgNoticePeriod { get; set; }
        public double buyoutPercentage { get; set; }
        public int maxNoticePeriod { get; set; }
        public int minNoticePeriod { get; set; }
        public double avgHikePercentage { get; set; }
        public double percLookingForChange { get; set; }
        public Nullable<bool> isSolrUpdated { get; set; }
        public string telephone { get; set; }
        public Nullable<bool> isDBSynced { get; set; }
    }
}
