//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace urNotice.Common.Infrastructure.Model.urNoticeAuthContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int Id { get; set; }
        public string companyName { get; set; }
        public string website { get; set; }
        public string headquarters { get; set; }
        public Nullable<long> size { get; set; }
        public string founded { get; set; }
        public string type { get; set; }
        public string industry { get; set; }
        public Nullable<long> revenue { get; set; }
        public string descriptions { get; set; }
        public string mission { get; set; }
        public string founder { get; set; }
        public System.DateTime lastUpdated { get; set; }
        public string createdBy { get; set; }
        public string lastUpdatedBy { get; set; }
        public System.DateTime createdDate { get; set; }
        public string universalName { get; set; }
        public double averageRating { get; set; }
        public long totalNumberOfRatings { get; set; }
        public long totalReviews { get; set; }
        public string guid { get; set; }
        public Nullable<bool> isDBSynced { get; set; }
    }
}
