//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace urNotice.Common.Infrastructure.Model.urNoticeAuthContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class contactU
    {
        public int Id { get; set; }
        public string username { get; set; }
        public string emailId { get; set; }
        public string heading { get; set; }
        public string message { get; set; }
        public System.DateTime dateTime { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Status { get; set; }
        public string ReplyMessage { get; set; }
        public string RepliedBy { get; set; }
        public string RepliedDateTime { get; set; }
        public string Type { get; set; }
        public Nullable<bool> isDBSynced { get; set; }
    }
}
