//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace urNotice.Common.Infrastructure.Model.urNoticeAuthContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class urnoticeAuthEntities : DbContext
    {
        public urnoticeAuthEntities()
            : base("name=urnoticeAuthEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<CompanyDesignationInfo> CompanyDesignationInfoes { get; set; }
        public virtual DbSet<CompanySubPart> CompanySubParts { get; set; }
        public virtual DbSet<CompanyType> CompanyTypes { get; set; }
        public virtual DbSet<contactU> contactUs { get; set; }
        public virtual DbSet<Designation> Designations { get; set; }
        public virtual DbSet<FacebookAuth> FacebookAuths { get; set; }
        public virtual DbSet<ForgetPassword> ForgetPasswords { get; set; }
        public virtual DbSet<linkedinAuth> linkedinAuths { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<RecommendedBy> RecommendedBies { get; set; }
        public virtual DbSet<Subscription> Subscriptions { get; set; }
        public virtual DbSet<UserAlert> UserAlerts { get; set; }
        public virtual DbSet<UserCompanyInfo> UserCompanyInfoes { get; set; }
        public virtual DbSet<UserEarningHistory> UserEarningHistories { get; set; }
        public virtual DbSet<UserEarning> UserEarnings { get; set; }
        public virtual DbSet<UserMessage> UserMessages { get; set; }
        public virtual DbSet<UserReputationMapping> UserReputationMappings { get; set; }
        public virtual DbSet<UserReputation> UserReputations { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<ValidateUserKey> ValidateUserKeys { get; set; }
    }
}
