//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace urNotice.Common.Infrastructure.Model.urNoticeAuthContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserEarning
    {
        public int Id { get; set; }
        public string username { get; set; }
        public string total { get; set; }
        public string approved { get; set; }
        public string pending { get; set; }
        public string currency { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string userType { get; set; }
        public Nullable<bool> isDBSynced { get; set; }
    }
}
