//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace urNotice.Common.Infrastructure.Model.urNoticeAuthContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCompanyInfo
    {
        public int Id { get; set; }
        public string companyId { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public string userId { get; set; }
        public string designationId { get; set; }
        public Nullable<int> salaryRange { get; set; }
        public Nullable<bool> isHappy { get; set; }
        public string reason { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<bool> shareReasonPublic { get; set; }
        public Nullable<bool> shareAsAnonymous { get; set; }
        public Nullable<bool> isDBSynced { get; set; }
    }
}
