//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace urNotice.Common.Infrastructure.Model.urNoticeRatingContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatGroup
    {
        public int Id { get; set; }
        public string chatMessage { get; set; }
        public string companyId { get; set; }
        public string locationId { get; set; }
        public string senderId { get; set; }
        public System.DateTime createdDate { get; set; }
        public short isInformative { get; set; }
        public short reportSpam { get; set; }
        public Nullable<bool> isDBSynced { get; set; }
    }
}
