//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace urNotice.Common.Infrastructure.Model.urNoticeRatingContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyDesignationXml
    {
        public int Id { get; set; }
        public string Designation { get; set; }
        public string Company { get; set; }
        public string Salary { get; set; }
        public string isUsed { get; set; }
        public Nullable<bool> isDBSynced { get; set; }
    }
}
