//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace urNotice.Common.Infrastructure.Model.urNoticeRatingContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyRating
    {
        public int Id { get; set; }
        public Nullable<double> workCulture { get; set; }
        public Nullable<double> employeeDevelopment { get; set; }
        public Nullable<double> appraisalProcess { get; set; }
        public Nullable<double> seniorManagement { get; set; }
        public Nullable<double> hrPolicies { get; set; }
        public Nullable<double> yourManager { get; set; }
        public string companyId { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
        public Nullable<double> overAllRating { get; set; }
        public Nullable<double> workLifeBalance { get; set; }
        public Nullable<double> salary { get; set; }
        public bool isSolrUpdated { get; set; }
        public Nullable<bool> isDBSynced { get; set; }
    }
}
