//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace urNotice.Common.Infrastructure.Model.urNoticeRatingContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jobgraphy
    {
        public int Id { get; set; }
        public string userId { get; set; }
        public bool isAnonymous { get; set; }
        public bool showAnonymous { get; set; }
        public string locationId { get; set; }
        public string designationId { get; set; }
        public string companyId { get; set; }
        public string name { get; set; }
        public Nullable<short> employeeType { get; set; }
        public string title { get; set; }
        public string body { get; set; }
        public string images { get; set; }
        public System.DateTime createdDate { get; set; }
        public bool isVerified { get; set; }
        public string verifiedBy { get; set; }
        public Nullable<short> storyType { get; set; }
        public string guid { get; set; }
        public Nullable<bool> isSolrUpdated { get; set; }
        public Nullable<bool> isDBSynced { get; set; }
    }
}
