//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace urNotice.Common.Infrastructure.Model.urNoticeRatingContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoticePeriodInfo
    {
        public int Id { get; set; }
        public string userId { get; set; }
        public bool isAnonymous { get; set; }
        public bool showAnonymous { get; set; }
        public string locationId { get; set; }
        public string designationId { get; set; }
        public Nullable<long> ctc { get; set; }
        public Nullable<int> maxNoticePeriod { get; set; }
        public Nullable<int> minNoticePeriod { get; set; }
        public Nullable<int> noticePeriodServed { get; set; }
        public Nullable<bool> buyOutOption { get; set; }
        public Nullable<bool> lookingForChange { get; set; }
        public Nullable<long> expectedCTC { get; set; }
        public string suggestion { get; set; }
        public string createdDate { get; set; }
        public string companyId { get; set; }
        public Nullable<System.DateTime> joiningDate { get; set; }
        public Nullable<System.DateTime> resigningDate { get; set; }
        public Nullable<bool> managerBehaviourChanged { get; set; }
        public bool isVerified { get; set; }
        public string verifiedBy { get; set; }
        public string guid { get; set; }
        public bool isHikeOffered { get; set; }
        public double hikePercentOffered { get; set; }
        public Nullable<bool> isDBSynced { get; set; }
    }
}
