//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace urNotice.Common.Infrastructure.Model.urNoticeRatingContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int Id { get; set; }
        public string userId { get; set; }
        public Nullable<short> workCulture { get; set; }
        public Nullable<short> employeeDevelopment { get; set; }
        public Nullable<short> appraisalProcess { get; set; }
        public Nullable<short> seniorManagement { get; set; }
        public Nullable<short> hrPolicies { get; set; }
        public Nullable<short> yourManager { get; set; }
        public string companyId { get; set; }
        public string locationId { get; set; }
        public System.DateTime createdDate { get; set; }
        public string suggestionToBoss { get; set; }
        public string suggestionToCompany { get; set; }
        public bool isVerified { get; set; }
        public string verifiedBy { get; set; }
        public string overAllRating { get; set; }
        public string guid { get; set; }
        public bool isAnonymous { get; set; }
        public Nullable<short> workLifeBalance { get; set; }
        public Nullable<short> salary { get; set; }
        public Nullable<bool> isDBSynced { get; set; }
    }
}
