//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace urNotice.Common.Infrastructure.Model.urNoticeRatingContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReasonsToStay
    {
        public int Id { get; set; }
        public string userId { get; set; }
        public bool updatedTechnology { get; set; }
        public bool suitingLocation { get; set; }
        public bool enoughOnSiteOpportunity { get; set; }
        public bool adequateSalary { get; set; }
        public bool executingMbaInProgress { get; set; }
        public bool contractCompulsions { get; set; }
        public bool recognitionAndAppreciation { get; set; }
        public bool supportiveTeam { get; set; }
        public bool personalReasons { get; set; }
        public string others { get; set; }
        public System.DateTime createdDate { get; set; }
        public string companyId { get; set; }
        public string locationId { get; set; }
        public bool isVerified { get; set; }
        public string verifiedBy { get; set; }
        public string guid { get; set; }
        public Nullable<bool> isDBSynced { get; set; }
    }
}
